version: '3.7'
services:
  dynamodb:
    image:  amazon/dynamodb-local
    container_name: todos_dynamodb
    hostname: dynamodb
    restart: always
    ports:
      - 8000:8000
    volumes:
      - dynamodata:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
  
volumes:
  dynamodata: {}