version: '3.7'
services:
  dynamodb:
    image:  amazon/dynamodb-local
    container_name: todos_dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      -  ./.dynamodb:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"