service: "todos-serverless"

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

functions:
  getTodos:
    handler: src/functions/getTodos.handle
    events:
      - http:
          path: /getTodos/{user_id}
          method: GET
          cors: true
  saveTodo:
    handler: src/functions/saveTodo.handle
    events:
      - http:
          path: /saveTodo/{user_id}
          method: POST
          cors: true
  updateTodo:
    handler: src/functions/updateTodo.handle
    events:
      - http:
          path: /updateTodo/{user_id}/{todo_id}
          method: PUT
          cors: true
  updateTodoDone:
    handler: src/functions/updateTodoDone.handle
    events:
      - http:
          path: /updateTodoDone/{user_id}/{todo_id}
          method: PATCH
          cors: true
  deleteTodo:
    handler: src/functions/deleteTodo.handle
    events:
      - http:
          path: /deleteTodo/{user_id}/{todo_id}
          method: DELETE
          cors: true
  
resources:
  Resources:
    dbCertificateUsers:
      Type: AWS::DynamoDB::Table      
      Properties:
        TableName: users
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH